/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package first;

/**
 *
 * @author USER
 */
public class dept_info extends javax.swing.JFrame {

    /**
     * Creates new form dept_info
     */
    String itemText;
    public dept_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediLab and Drug Store  Information System");
        setLocation(new java.awt.Point(300, 150));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 222, 211));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiology", "ENT", "Gynaecology", "Nephrology", "Neurology", "Orthopaedics", "Pharmacy", "Physiotherapy" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("View Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Go to Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        itemText = (String)jComboBox1.getSelectedItem();
        jTextArea1.setText(null);
        if(itemText=="Cardiology")
        {
        jTextArea1.setText("This department provides medical care to patients who have problems with their heart or circulation. It treats people on an outpatient basis.\n" +
"Typical procedures performed include:\n" +
"•	electrocardiogram (ECG) and exercise tests to measure heart function\n" +
"•	echocardiograms (ultrasound scan of the heart)\n" +
"•	scans of the carotid artery in your neck to determine stroke risk\n" +
"•	24-hour blood pressure tests\n" +
"•	insertion of pacemakers\n" +
"•	cardiac catheterisation (coronary angiography) to see if there are any blocks in your arteries.");
        }
        else if(itemText=="ENT"){
        jTextArea1.setText("The ENT department provides care for patients with a variety of problems, including:\n" +
"•	general ear, nose and throat diseases\n" +
"•	neck lumps\n" +
"•	cancers of the head and neck area\n" +
"•	tear duct problems\n" +
"•	facial skin lesions\n" +
"•	balance and hearing disorders\n" +
"•	snoring and sleep apnoea\n" +
"•	ENT allergy problems\n" +
"•	salivary gland diseases\n" +
"•	voice disorders.");
        }
        else if(itemText=="Gynaecology")
        {
         jTextArea1.setText("These departments investigate and treat problems of the female urinary tract and reproductive organs, such as endometritis, infertility and incontinence.\n" +
"They also provide a range of care for cervical smear screening and post-menopausal bleeding checks.\n" +
"They usually have:\n" +
"•	a specialist ward\n" +
"•	day surgery unit\n" +
"•	emergency gynaecology assessment unit\n" +
"•	outpatient clinics.");
        }
         else if(itemText=="Nephrology")
        {
         jTextArea1.setText("This department monitors and assesses patients with kidney (renal) problems.\n" +
"Nephrologists (kidney specialists) will liaise with the transplant team in cases of kidney transplants.\n" +
"They also supervise the dialysis day unit for people who are waiting for a kidney transplant or who are unable to have a transplant for any reason.");
        }
          else if(itemText=="Neurology")
        {
         jTextArea1.setText("This unit deals with disorders of the nervous system, including the brain and spinal cord. It's run by doctors who specialise in this area (neurologists) and their staff.\n" +
"There are also paediatric neurologists who treat children. Neurologists may also be involved in clinical research and clinical trials.\n" +
"Specialist nurses (epilepsy, multiple sclerosis) liaise with patients, consultants and GPs to help with any problems that may occur between outpatient appointments.");
        }
           else if(itemText=="Orthopaedics")
        {
         jTextArea1.setText("Orthopaedic departments treat problems that affect your musculoskeletal system. That's your muscles, joints, bones, ligaments, tendons and nerves.\n" +
"The doctors and nurses who run this department deal with everything from setting bone fractures to carrying out surgery to correct problems such as torn ligaments and hip replacements.\n" +
"Orthopaedic trauma includes fractures and dislocations as well as musculoskeletal injuries to soft tissues.");
        }
            else if(itemText=="Pharmacy")
        {
         jTextArea1.setText("The hospital pharmacy is run by pharmacists, pharmacy technicians and attached staff.\n" +
"It's responsible for drug-based services in the hospital, including:\n" +
"•	the purchasing, supply and distribution of medication and pharmaceuticals\n" +
"•	outpatient dispensing\n" +
"•	clinical and ward pharmacy\n" +
"•	the use of drugs.\n" +
"A pharmacy will provide a drug formulary for hospital doctors to use as a guide. It will also help supervise any clinical trial management and ward drug-use review.");
        }
             else if(itemText=="Physiotherapy")
        {
         jTextArea1.setText("Physiotherapists promote body healing, for example after surgery, through therapies such as exercise and manipulation.\n" +
"This means they assess, treat and advise patients with a wide range of medical conditions. They also provide health education to patients and staff on how to do things more easily.\n" +
"Their services are provided to patients on the wards, in the physiotherapy department itself and in rehabilitation units.\n" +
"Physiotherapists often work closely with orthopaedic teams.");
        }
        else
        {
        jTextArea1.setText(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dept_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dept_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dept_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dept_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dept_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
